### ISSUE TITLE
Doesn't ask to regen slideshow after adding media to collection

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#122] opened 2022-12-01 21:45 UTC
Should use same behavior as the other add media (ask to regen after adding)

**Comment by punctuations** [comment] 2022-12-02 01:26
It should behave the same, no?

The way that the collections script works is by calling the add_media function used in add media.

(code here https://github.com/timberline-secondary/hackerspace-scripts-2/blob/master/scripts/TVs/collection_add_media.py#L29)

**Comment by tylerecouture** [comment] 2022-12-02 06:56
Let me double check it.

**Comment by punctuations** [comment] 2022-12-10 00:57
What's the status on this? @tylerecouture

**Comment by tylerecouture** [comment] 2022-12-10 01:13
I don't remember. Gonna close.

**Comment by punctuations** [comment] 2022-12-13 18:08
duplicate of latest stuff in #111 ?

**Closed** 2022-12-13 23:35 UTC
